/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.5.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as events from "../events";
import type * as openai from "../openai";
import type * as openai_events from "../openai_events";
import type * as openai_interface from "../openai_interface";
import type * as openai_scheduler from "../openai_scheduler";
import type * as trips from "../trips";
import type * as utils from "../utils";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  events: typeof events;
  openai: typeof openai;
  openai_events: typeof openai_events;
  openai_interface: typeof openai_interface;
  openai_scheduler: typeof openai_scheduler;
  trips: typeof trips;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
