import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import RootWrapper from './providers/RootWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <RootWrapper>
          <body className={inter.className}>{children}</body>
        </RootWrapper>
      </head>
    </html>
  );
}
