import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RootWrapper from './providers/RootWrapper';
import { ThemeProvider } from './providers/ThemeProvider';
import { ModeToggle } from '@/components/ui/darkMode';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <RootWrapper>
            <body className={inter.className}>{children}</body>
          </RootWrapper>
        </ThemeProvider>
      </head>
    </html>
  );
}
